import '../app/globals.css';
import { Navigation } from './components/Navigation.jsx';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				{children}
				<Navigation />
			</body>
		</html>
	);
}
